### PR TITLE
add voices #141 #23

### PR DESCRIPTION
**Pull request by vikasgola**
Added a drop-down menu to select the voices.

Thanks for contributing. Your contribution might help someone understand the concepts better.

However, to make sure things are working properly, here's a checklist. Just make sure you check them.
- [x] I am reading these checkboxes. 
- [x] Read [contribution guidelines](/docs/Contributing.md)
- [x] Screenshots

closed_menu
open_menu

### CODE REVIEW

**Comment by gauthamzz** [comment]
This is awesome :sunglasses: 
I love it :heart: 

Could you just reduce the text box size and font size,it looks a bit too big.

**Comment by vikasgola** [comment]
Ok sure However in my opinion that's ok...

**Comment by gauthamzz** [comment]
Yes

But i'm not a big fan of this 
deepinscreenshot_select-area_20180625142006

Plus users only change voice once or twice. They shouldnt have to see things that they dont use very often. So a lesser size would work .

**Comment by vikasgola** [comment]
@gauthamzz I decreased the font-size but that doesn't work. So, I changed the css to overflow-y: hidden that worked.

with small text and simple box 
anna_2

with css overflow property
anna_1

**Comment by gauthamzz** [comment]
yeah that works. 

so you cant make the text box smaller, its fine . we can do that as another issue

**Comment by vikasgola** [comment]
@gauthamzz completed.

**Comment by gauthamzz** [comment]
Great work, thanks :+1:

**Pull request merged**
