### PR TITLE
changed the design of the popup

### PR DESCRIPTION
**Pull request by pbteja1998**
- Solves #27 
- Improved the design of `popup.html`
- most of the `css` is based on some other chrome extension called `Green Leaf`
- Screenshots were attached below for reference
screenshot_20171210_065014
screenshot_20171210_065131
screenshot_20171210_065150

### CODE REVIEW

**Comment by gauthamzz** [comment]
Wow this looks amazing

**Review by gauthamzz — APPROVED** [review]

**Comment by gauthamzz** [comment]
Im sorry , but after merging this issue . The assistant stopped working , The toggle even when turned on gets turned off.

**Comment by pbteja1998** [comment]
- First of all, I didn't go through the entire code as I thought for just adding css to pop up, it is unnecessary to go through the entire code. 
- I can see some reasons as to why the assistant stopped working, I forgot to include Javascript files in `popup.html`.(just observed it) 
- I did not test anything. I will get back to you by tonight possibly with other pr to solve this.

**Comment by pbteja1998** [comment]
Also, I thought that the toggle buttons are just dummy buttons. I thought that it is not implemented. But i think toggle button functionality is implemented. So, I should change that too.

**Comment by gauthamzz** [comment]
also activate anna and speech recognition both are same thing only. only need of one . we can add more functionalities as we go .

**Comment by pbteja1998** [comment]
Yeah, I just gave it as a reference. As I said before, I did only the static part of it.

**Pull request merged**
