### PR TITLE
Reduce popup height

### LINKED ISSUE #122: Reduce pop up size
The pop up size is too large relative to the screen size.
The settings ,help buttons also are too large

Reduce the size of pop up.
Follow up of #108.

### PR DESCRIPTION
**Pull request by pradeepgangwar**
screenshot from 2018-01-03 15-59-31

This is how the new popup looks. Let me know any changes, if required.

closes #122

### CODE REVIEW

**Review by gauthamzz — APPROVED** [review]

**Comment by gauthamzz** [comment]
Looks good , do you think the setting and help button is too big ?

**Comment by lalitmee** [comment]
I think footer width is also not appropriate. The footer is also somewhat wider than normal.

**Comment by pradeepgangwar** [comment]
I will try to make them small.

**Comment by pradeepgangwar** [comment]
screenshot from 2018-01-03 16-40-09

@gauthamzz Sir, this is how it looks now. Let me know further modifications.

**Comment by gauthamzz** [comment]
Bro don’t call me sir

**Comment by gauthamzz** [comment]
Thanks for the pr

**Pull request merged**
