### PR TITLE
How it works documentation

### PR DESCRIPTION
**Pull request by mmBabol**
Documentation on how to use Anna. Documentation includes commands for:
- Weather
- Websites
- Navigation
- Other

Display link on the bottom for a live demo preview.

### CODE REVIEW

**Comment by gauthamzz** [comment]
Could you wait some time. I'm making images for this part . We can add them to the docs.

**Comment by mmBabol** [comment]
Okay I'll wait till you're done, no problem. Thanks

**Comment by gauthamzz** [comment]
Its added see the image files in https://github.com/Anna-Assistant/Anna/tree/master/docs

link the images and use the same sections as the images as well.  
Suggestions for improvement:
- Add more sample commands than the one which is the pictures
- Extra features or features which are being developed on github

**Comment by mmBabol** [comment]
Does that look better @gauthamzz ?

**Review by gauthamzz — APPROVED** [review]

**Comment by gauthamzz** [comment]
It's great I merged it

**Comment by gauthamzz** [comment]
Can you modify this 

It should be like this 

## Automated Actions 

### Reverse image search 
Description: With the help of Anna user can select and crop a part of the screen, which is then used to reverse image search on Google images. 

// as image over here
User says: 
Hey reverse search 
Hey what is this 
// Should have more examples than the image.

**Pull request merged**
